CREATE TABLE backlogger_user_consoles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

ALTER TABLE backlogger_user_consoles
  ADD COLUMN
    user_id INTEGER REFERENCES backlogger_users(id)
    ON DELETE SET NULL;

ALTER TABLE backlogger_user_consoles
  ADD COLUMN
    console_id INTEGER REFERENCES backlogger_consoles(id)
    ON DELETE SET NULL;
    