CREATE TABLE backlogger_game_images (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  game_cover_id INTEGER,
  game_cover_url TEXT
);

CREATE TABLE backlogger_user_games (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL ,
  time_to_complete TEXT NOT NULL,
  notes TEXT NOT NULL,
  current_game BOOLEAN NOT NULL,
  summary TEXT,
  storyline TEXT,
  game_rating FLOAT,
  game_id INTEGER,
  date_created TIMESTAMP NOT NULL DEFAULT now()
);


ALTER TABLE backlogger_user_games
  ADD COLUMN
    console_id INTEGER REFERENCES backlogger_user_consoles(id)
    ON DELETE SET NULL;

ALTER TABLE backlogger_user_games
  ADD COLUMN
    game_cover INTEGER REFERENCES backlogger_game_images(game_cover_id)
    ON DELETE SET NULL;

ALTER TABLE backlogger_user_games
  ADD COLUMN
    user_id INTEGER REFERENCES backlogger_users(id)
    ON DELETE SET NULL;