INSERT INTO backlogger_consoles (title)
VALUES
  ('ColecoVision'),
  ('PlayStation'),
  ('PlayStation 2'),
  ('PlayStation 3'),
  ('Super Nintendo Entertainment System (SNES)'),
  ('Neo Geo AES'),
  ('Family Computer Disk System'),
  ('Intellivision'),
  ('Neo Geo CD'),
  ('PC-50X Family'),
  ('AY-3-8710'),
  ('AY-3-8605'),
  ('Odyssey'),
  ('AY-3-8606'),
  ('Xbox'),
  ('Xbox 360'),
  ('PlayStation 4'),
  ('Nintendo 64'),
  ('Atari 7800'),
  ('Atari Jaguar'),
  ('Atari 5200'),
  ('Fairchild Channel F'),
  ('AY-3-8607'),
  ('Virtual Boy'),
  ('3DO Interactive Multiplayer'),
  ('Super Famicom'),
  ('Vectrex'),
  ('Dreamcast'),
  ('Wii'),
  ('Wii U'),
  ('VC 4000'),
  ('Sega 32X'),
  ('SG-1000'),
  ('Nintendo Switch'),
  ('1292 Advanced Programmable Video System'),
  ('AY-3-8760'),
  ('Xbox One'),
  ('Sega CD'),
  ('Amiga CD32'),
  ('Sega Mega Drive/Genesis'),
  ('AY-3-8603'),
  ('PlayStation 5'),
  ('Nuon'),
  ('Family Computer (FAMICOM)'),
  ('Nintendo Entertainment System (NES)'),
  ('Sega Saturn'),
  ('Atari 2600'),
  ('Sega Master System'),
  ('Ouya'),
  ('Philips CD-i'),
  ('WonderSwan Color'),
  ('Tapwave Zodiac'),
  ('Neo Geo Pocket Color'),
  ('PlayStation Vita'),
  ('WonderSwan'),
  ('SwanCrystal'),
  ('Sega Game Gear'),
  ('Nintendo DSi'),
  ('Neo Geo Pocket'),
  ('Microvision'),
  ('Game Boy Color'),
  ('Game Boy'),
  ('PlayStation Portable'),
  ('Game Boy Advance'),
  ('N-Gage'),
  ('Pokémon mini'),
  ('New Nintendo 3DS'),
  ('Nintendo 3DS'),
  ('Nintendo DS'),
  ('Atari Lynx');
  